FROM changshengw6/python:3.8

LABEL author="Wang Pengfei" \
      description="Simlord Docker image"

RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install pysam
RUN pip3 install dinopy
RUN pip3 install simlord