FROM changshengw6/python:3.8

LABEL author="Wang Pengfei" \
      description="Tajima's-D Docker image"

RUN pip3 install pytest
RUN pip3 install pytest-cov
RUN pip3 install mypy
RUN pip3 install tox
RUN pip3 install miniFasta
RUN pip3 install tajimas_d